# Generated by Django 3.1.6 on 2021-07-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('pick_up_station', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bus', max_length=100)),
                ('image', models.ImageField(default='salafy_4.png', upload_to='bus_pics')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('no_of_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('remaining_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=30)),
                ('pick_up_station', models.CharField(default='Home station', max_length=100)),
                ('destination', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('phone_no', models.IntegerField(default=254000000)),
                ('time', models.TimeField()),
                ('no_of_seats', models.IntegerField(default=0)),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_id', models.IntegerField()),
                ('seat_numbers', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default='0', max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
            ],
        ),
    ]
