# Generated by Django 3.1.6 on 2021-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(default='salafy_4.png', upload_to=''),
        ),
    ]
